### ISSUE TITLE
Request for latest bindings

### ISSUE THREAD

**Issue by Bahlph** [Cvelth/vkma_generator#1]
VMA has gone through several breaking changes since the generation of these bindings, and I'd appreciate it if the VKMA bindings were regenerated for use with the latest release of VMA.  Additionally / Alternatively, it would be nice to have detailing in the README regarding how anyone could generate the bindings themselves.

**Comment by Cvelth** [comment]
Hi, @Bahlph, thanks for the issue! I had no idea anyone was using this old project of mine!

I have updated the bindings, but take note that they are not tested, so there are probably some problems.
If you run into any, don't hesitate to make an issue.

Additionally, I wrote a super-short list of what one would need to do to regenerate the bindings, hopefully that's helpful.

**Comment by Bahlph** [comment]
Thanks so much for the response!

There seem to be some changes that need to be made to the `vkma_bindings.hpp`s to get them up to date.  So far I've made the following edits
- `VkmaAllocatorCreateInfo` and `VkmaTotalStatistics` have new members
- `vmaCalculateStats` was renamed to `vmaCalculateStatistics`
- `vkmaEndDefragmentation` and `vkmaVirtualFree` return void now
- `vkmaBeginDefragmentationPass` no longer takes a const `VkmaDefragmentationPassMoveInfo`
- `vkmaEndDefragmentationPass` no longer takes a const `VkmaDefragmentationPassMoveInfo`

and I plan to submit a PR as soon as everything is up to date, but I have run into one problem that I can't figure out so far.  As listed above, `VkmaAllocatorCreateInfo` has new members
- `PFN_vkGetDeviceBufferMemoryRequirements vkGetDeviceBufferMemoryRequirements;`
- `PFN_vkGetDeviceImageMemoryRequirements vkGetDeviceImageMemoryRequirements;`

but when trying to add them, generating the XML warns
```
Warning: Fail to append an undefined type: 'PFN_vkGetDeviceBufferMemoryRequirements'.
Warning: Fail to append an undefined type: 'PFN_vkGetDeviceImageMemoryRequirements'.
```
which causes the HPP generation to fail with `caught exception: Spec error on line 242: struct member uses unknown type <PFN_vkGetDeviceBufferMemoryRequirements>` and I'm not sure what to do about that.

P.S. [My edited bindings](https://github.com/Cvelth/vkma_generator/files/8839201/vkma_bindings.txt) are attached in case it helps.

P.P.S. Take your time and answer at your convenience!

**Comment by Cvelth** [comment]
I've looked into the situation and is somewhat embarrassed about mistakes I made with the manual bindings :D Good job with catching those. Feel free to submit the PRs for these fixes already.

As for unknown `PFN_vkGetDeviceBufferMemoryRequirements` and `PFN_vkGetDeviceImageMemoryRequirements` types - these are vulkan 1.3 and as of now a somewhat outdated `v1.2.166` of vulkan headers is used - hence, these are not known to the generator. I'll take a look at updating the headers, hopefully that would solve the problem.

UPDATE: Header update went even smoother than I expected! Please let me know if this solved the problem on your end as well.

**Comment by Bahlph** [comment]
Ah, that explains that!

I've submitted a PR which fixes all the problems that I could solve myself.  However, there are still a couple of issues remaining that I'm unsure about:
- `VirtualBlock::setVirtualAllocationUserData` is generated weirdly; it attempts to create a variable of type `void`, pass its address into a function, and then return it.  The problem can be fixed by changing the final hpp to create a `void*`, pass it directly into the function, and not return anything, but I'm not sure what's causing it to generate that way.
- Something is wrong with `typename ResultValueType<DefragmentationPassMoveInfo>::type end( DefragmentationContext context ) const`.  As of now, I've just commented out the function to be figured out later.
- For some reason vkma::createResultValue doesn't work for the following, and I've commented them out as well, to be figured out later.
  - `createVirtualBlockUnique`
  - `beginDefragmentationUnique`
  - `virtualAllocateUnique`

Altogether not huge issues, but it's probably best to not rely on fixes that either completely remove functions or require editing the final generated file directly.

**Comment by Cvelth** [comment]
Thank you for investigating all these! I'll take a look.

**Comment by Cvelth** [comment]
1. `VirtualBlock::setVirtualAllocationUserData` problem is pretty common. This is one of the reasons why manual bindings were unavoidable - but luckily a fix is simple, all we need to do is to make `pUserData` a `const` pointer.
3. Can you elaborate on what error/problem you're getting with this one? It doesn't look any different from the functions next to it on a quick look.
4. Same here, what's the error you're seeing?

**Comment by Bahlph** [comment]
1. Huh, thanks for the fix!
2. I'm getting `two functions with the same parameter types but different exception specifications cannot be overloaded` but if `VKMA_NOEXCEPT` is added to match the exception specifications, I get `cannot overload functions distinguished by return type alone`.
3. I'm getting `no instance of overloaded function "vkma::createResultValue" matches the argument list` for all three of those functions.  Not sure why that's happening when, like you said, it looks like it's in exactly the same format as surrounding functions.

**Comment by Cvelth** [comment]
Good news. I looks like both the remaining issues are fixed, let's continue this discussion on the PR.
